isReturning = false; // Adiciona uma variável para rastrear se a espada está voltando
returnDistance = false // Distância em pixels que a espada deve percorrer antes de retornar
start_x = x; // Armazena a posição inicial X da espada
start_y = y; // Armazena a posição inicial Y da espada
stopped = false
distance_travelled = 0
pickable = false
maxSpeed = 10
accel = 0.2